---
title: "Buffalo Blizzards"
author: "Kevin Havis"
format: html
---

## Introduction

## Reading the data

```{r}
library(tidyverse)
library(knitr)
library(ggridges)
```


```{r}
df <- read.csv('buffalo_weather.csv')

head(df)
```

```{r}
df <- df |>
  
  # Rename columns
  rename_with(~str_to_lower(.x), .cols = everything()) |> 
  
  # Remove duplicate headers
  filter(season != "SEASON") |> 
  
  # Replace T[race] with zero, convert to numerical, drop empty rows
  # We allow blanks to be coerced to NAs
  # There is also a really sneaky comma in the data we need to remove
  mutate(across(2:last_col(), str_replace, "T", "0")) |>
  mutate(across(2:last_col(), str_replace, ",", "")) |>  # The comma of '76
  mutate(across(2:last_col(), ~ as.numeric(.))) |> 
  drop_na(2:last_col()) |> 
  
  # We don't need annual right now
  select(-annual) |> 
  
  # Convert to long format
  pivot_longer(2:last_col(), names_to = "month", values_to = "snowfall") |> 
  
  # Create a new year column by splitting the season column
  # Season is still useful so we will keep it
  separate(season, into = c("year_1", "year_2"), sep = "-", remove = FALSE) |>
  
  # Correct the ending year format
  mutate(season_prefix = str_sub(season, 1,2)) |> 
  mutate(year_2 = str_c(season_prefix, year_2)) |> 
  
  # Assign months across a season to the corresponding years
  mutate(year = as.numeric(case_when(
    month %in% c("jul", "aug", "sep", "oct", "nov", "dec") ~ year_1,
    month %in% c("jan", "feb", "mar", "apr", "may", "jun") ~ year_2
    )
  )) |> 
  
  # Yes this is an ugly hack but the 1900s won't mind
  mutate(year = if_else(year == 1900, 2000, year)) |> 
  
  # Fix the month names and create a date type column for future flexibility
  mutate(month = case_when(
    month == "jan" ~ "January",
    month == "feb" ~ "February",
    month == "mar" ~ "March",
    month == "apr" ~ "April",
    month == "may" ~ "May",
    month == "jun" ~ "June",
    month == "jul" ~ "July",
    month == "aug" ~ "August",
    month == "sep" ~ "September",
    month == "oct" ~ "October",
    month == "nov" ~ "November",
    month == "dec" ~ "December"
  )) |> 
  mutate(date = make_date(year, match(month, month.name), 1)) |> 
  select(date, season, year, month, snowfall)
```

```{r}
month_levels <- c(
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December"
)

df <- df |> 
  mutate(month = factor(month, levels = month_levels))
```


## Plot blizzards

```{r}
library(viridis)
library(hrbrthemes)

ggplot(df, aes(x = snowfall, y = month, fill= ..x..)) +
  geom_density_ridges_gradient(scale =3, rel_min_height = 0.001, gradient_lwd = 1) +
  scale_fill_viridis(name = "snowfall", option = "mako", direction = -1) +
  labs(title = 'Buffalo Snowfall 1940 - 2023') +
  theme_minimal() +
  scale_y_discrete(limits = rev(month_levels))


```

```{r}

blizzards <- df |> 
  filter(snowfall > 60)

ggplot(df, aes(x = date, y = snowfall)) +
  geom_bar(stat = "identity", just = 1) +
  geom_bar(stat = "identity", width = .20 * nrow(df), data = blizzards, fill = "#6280a5") +
  labs(title = 'Snowfall by Month', x = 'Month', y = 'Snowfall') +
  theme_minimal()
```

```{r}
# Blizzard of 77
b_77 <- df |> 
  filter(year > 1970 & year < 1980) |> 
  mutate(blizzard = snowfall == max(snowfall))

ggplot(b_77, aes(x = date, y = snowfall, fill=blizzard)) +
  geom_bar(stat = "identity", just = 1) +
  labs(title = "Great Blizzard of '77", x = 'Month', y = 'Snowfall') +
  annotate(geom = 'label', x=as.Date('1977-01-01'), y = 80, label = "Great Blizzard of '77") +
  theme_minimal() +
  scale_fill_manual(values = c("TRUE" = "#6280a5"))

```


```{r}
# 06 October Surprise
b_06 <- df |> 
  filter(month == "October") |> 
  mutate(blizzard = snowfall == max(snowfall))

ggplot(b_06, aes(x = year, y = snowfall, fill=blizzard)) +
  geom_bar(stat = "identity", just = 1) +
  labs(title = "The October Surprise", x = 'Octobers', y = 'Snowfall') +
 annotate(geom = 'label', x=2006, y = 25, label = "The October Surprise") +
  theme_minimal() +
  scale_fill_manual(values = c("TRUE" = "#6280a5"))

```

```{r}
# Christmas Blizzard of 2022
b_22 <- df |> 
  filter(month == "December" & year > 2014) |> 
  mutate(blizzard = snowfall == max(snowfall))


ggplot(b_22, aes(x = date, y = snowfall, fill=blizzard)) +
  geom_bar(stat = "identity", just = 1) +
  labs(title = "Great Blizzard of '77", x = 'Month', y = 'Snowfall') +
  #annotate(geom = 'label', x=as.Date('1977-01-01'), y = 80, label = "Great Blizzard of '77") +
  theme_minimal() +
  scale_fill_manual(values = c("TRUE" = "#6280a5"))

```
